// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA00qf2fpwTmzEiIHj8S2uJc2DmrJyPu-k',
    appId: '1:362321706918:web:57b02b569e06fc0d181967',
    messagingSenderId: '362321706918',
    projectId: 'homefinder-flutter-project',
    authDomain: 'homefinder-flutter-project.firebaseapp.com',
    storageBucket: 'homefinder-flutter-project.appspot.com',
    measurementId: 'G-KCSE9EN21Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdRCJxaLVZDkf9G3f_uUDahgYn2hdytmk',
    appId: '1:362321706918:android:d895f75f8c11d635181967',
    messagingSenderId: '362321706918',
    projectId: 'homefinder-flutter-project',
    storageBucket: 'homefinder-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXsxD3EtpOvi9Ivm3aI5k2ChJaA8AB6UY',
    appId: '1:362321706918:ios:8b0d4c106321efdd181967',
    messagingSenderId: '362321706918',
    projectId: 'homefinder-flutter-project',
    storageBucket: 'homefinder-flutter-project.appspot.com',
    iosClientId: '362321706918-j7nrgf1srv65fu2nm98und7g9g552r9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.homefinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXsxD3EtpOvi9Ivm3aI5k2ChJaA8AB6UY',
    appId: '1:362321706918:ios:8b0d4c106321efdd181967',
    messagingSenderId: '362321706918',
    projectId: 'homefinder-flutter-project',
    storageBucket: 'homefinder-flutter-project.appspot.com',
    iosClientId: '362321706918-j7nrgf1srv65fu2nm98und7g9g552r9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.homefinder',
  );
}
